import { setupNav } from "./ui/nav.js";
import { setupProjectCards } from "./ui/cards.js";
import { setupShadowGenerator } from "./tools/shadow.js";
import { setupRadiusGenerator } from "./tools/radius.js";
import { setupPaletteGenerator } from "./tools/palette.js";
import { setupGradientGenerator } from "./tools/gradient.js";
import { setupTextShadowGenerator } from "./tools/text-shadow.js";
import { setupTransformGenerator } from "./tools/transform.js";
import { setupGlassGenerator } from "./tools/glass.js";
import { setupGridGenerator } from "./tools/grid.js";
import { setupFlexboxGenerator } from "./tools/flexbox.js";
import { setupAnimationGenerator } from "./tools/animation.js";
import { setupFilterGenerator } from "./tools/filter.js";
import { setupPxToRemConverter } from "./tools/px-to-rem.js";
import { setupRemToPxConverter } from "./tools/rem-to-px.js";
import { setupPxToEmConverter } from "./tools/px-to-em.js";
import { setupHexToRgbConverter } from "./tools/hex-to-rgb.js";

setupNav();
setupProjectCards();
setupShadowGenerator();
setupRadiusGenerator();
setupPaletteGenerator();
setupGradientGenerator();
setupTextShadowGenerator();
setupTransformGenerator();
setupGlassGenerator();
setupGridGenerator();
setupFlexboxGenerator();
setupAnimationGenerator();
setupFilterGenerator();
setupPxToRemConverter();
setupRemToPxConverter();
setupPxToEmConverter();
setupHexToRgbConverter();
