import { setupNav } from "./ui/nav.js";
import { setupShadowGenerator } from "./tools/shadow.js";
import { setupRadiusGenerator } from "./tools/radius.js";
import { setupPaletteGenerator } from "./tools/palette.js";
import { setupGradientGenerator } from "./tools/gradient.js";
import { setupTextShadowGenerator } from "./tools/text-shadow.js";
import { setupTransformGenerator } from "./tools/transform.js";
import { setupGlassGenerator } from "./tools/glass.js";
import { setupGridGenerator } from "./tools/grid.js";
import { setupFlexboxGenerator } from "./tools/flexbox.js";
import { setupAnimationGenerator } from "./tools/animation.js";
import { setupFilterGenerator } from "./tools/filter.js";

setupNav();
setupShadowGenerator();
setupRadiusGenerator();
setupPaletteGenerator();
setupGradientGenerator();
setupTextShadowGenerator();
setupTransformGenerator();
setupGlassGenerator();
setupGridGenerator();
setupFlexboxGenerator();
setupAnimationGenerator();
setupFilterGenerator();
